In [2]:
import torch
import numpy as np

### Torch and Numpy - rand

In [11]:
xt = torch.rand(3,2)
print(xt)

xn = np.random.rand(3,2)
print(xn)

print(f'type of xt = {type(xt)}, type of xn = {type(xn)}')

tensor([[0.8383, 0.4117],
        [0.4163, 0.3539],
        [0.2092, 0.1596]])
[[0.43410661 0.50036401]
 [0.63341489 0.41355207]
 [0.77858689 0.10970461]]
type of xt = <class 'torch.Tensor'>, type of xn = <class 'numpy.ndarray'>


In [12]:
xt = torch.rand(3,2,3)
print(xt)

xn = np.random.rand(3,2,3)
print(xn)

print(f'type of xt = {type(xt)}, type of xn = {type(xn)}')

tensor([[[0.3830, 0.8086, 0.6509],
         [0.7013, 0.8648, 0.6911]],

        [[0.6621, 0.4616, 0.9073],
         [0.1162, 0.3834, 0.7430]],

        [[0.7844, 0.7168, 0.8787],
         [0.3361, 0.4746, 0.6394]]])
[[[0.14755787 0.32352626 0.60663712]
  [0.14141418 0.1687627  0.29244438]]

 [[0.52929288 0.98311014 0.21345911]
  [0.15292472 0.58464494 0.17211287]]

 [[0.32809916 0.63612133 0.14327148]
  [0.53356943 0.0276043  0.83645594]]]
type of xt = <class 'torch.Tensor'>, type of xn = <class 'numpy.ndarray'>


In [16]:
print(xt*xn)

tensor([[[0.0565, 0.2616, 0.3948],
         [0.0992, 0.1459, 0.2021]],

        [[0.3505, 0.4538, 0.1937],
         [0.0178, 0.2242, 0.1279]],

        [[0.2574, 0.4560, 0.1259],
         [0.1793, 0.0131, 0.5349]]], dtype=torch.float64)


### Slicing

In [28]:
x = torch.rand(3,4)
y = np.random.rand(3,4)

print(x)

tensor([[0.6587, 0.1773, 0.3811, 0.3104],
        [0.8058, 0.6570, 0.2945, 0.7069],
        [0.9050, 0.3028, 0.6840, 0.8042]])


In [34]:
print(x[:, 1])   # only column #1
print(x[:, 1:3]) # only column #1 to until #3

tensor([0.1773, 0.6570, 0.3028])
tensor([[0.1773, 0.3811],
        [0.6570, 0.2945],
        [0.3028, 0.6840]])


In [35]:
print(x[1:, :]) # from #1th row until all row and all columns

tensor([[0.8058, 0.6570, 0.2945, 0.7069],
        [0.9050, 0.3028, 0.6840, 0.8042]])


In [36]:
# from row #1 row until all row
# from column #1 to until #3
print(x[1:, 1:3])

tensor([[0.6570, 0.2945],
        [0.3028, 0.6840]])


### Resizing

In [41]:
print(x.size())
y = x.view(12) # one dimentional
print(y)

torch.Size([3, 4])
tensor([0.6587, 0.1773, 0.3811, 0.3104, 0.8058, 0.6570, 0.2945, 0.7069, 0.9050,
        0.3028, 0.6840, 0.8042])


In [48]:
y = x.view(2, 6) # 2x6
print(y)

tensor([[0.6587, 0.1773, 0.3811, 0.3104, 0.8058, 0.6570],
        [0.2945, 0.7069, 0.9050, 0.3028, 0.6840, 0.8042]])


### Simple Torch operations

In [22]:
x = torch.rand(2,3)
y = torch.rand(2,3)

# ADDITIONS         # SUB, MUL, DIV
z = x + y           # -    *    /
z = torch.add(x, y) # sub  mul  div
y.add_(x) # inplace # 



tensor([[0.1490, 1.0534, 1.0373],
        [0.5835, 1.7363, 1.7754]])

### Torch <-> Numpy conversion

In [55]:
# torch to numpy
print(x)
print(type(x))

n = x.numpy()
print(n)
print(type(n))

tensor([[1.6587, 1.1773, 1.3811, 1.3104],
        [1.8058, 1.6570, 1.2945, 1.7069],
        [1.9050, 1.3028, 1.6840, 1.8042]])
<class 'torch.Tensor'>
[[1.6587033 1.1772724 1.3810623 1.310389 ]
 [1.8058476 1.657022  1.2945385 1.7069143]
 [1.9049897 1.3028443 1.6839669 1.804187 ]]
<class 'numpy.ndarray'>


#### Important - deep copy

In [56]:
x.add_(1) # inplace add 1

print(x)
print(n) # 1 is added to "n" too

tensor([[2.6587, 2.1773, 2.3811, 2.3104],
        [2.8058, 2.6570, 2.2945, 2.7069],
        [2.9050, 2.3028, 2.6840, 2.8042]])
[[2.6587033 2.1772723 2.3810623 2.310389 ]
 [2.8058476 2.657022  2.2945385 2.7069144]
 [2.9049897 2.3028443 2.6839669 2.804187 ]]


In [59]:
n = x.clone().numpy()
x.add_(1)

print(x)
print(n) # did not added 

tensor([[4.6587, 4.1773, 4.3811, 4.3104],
        [4.8058, 4.6570, 4.2945, 4.7069],
        [4.9050, 4.3028, 4.6840, 4.8042]])
[[3.6587033 3.1772723 3.3810623 3.310389 ]
 [3.8058476 3.657022  3.2945385 3.7069144]
 [3.9049897 3.3028443 3.6839669 3.804187 ]]
